# Generated by Django 5.1.5 on 2025-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
